// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBv4qE6-cD_Ct4tt3DWt_jtjDW9w8euyM',
    appId: '1:521427089788:web:9ae3169773188550d08cf9',
    messagingSenderId: '521427089788',
    projectId: 'freizeitnotes-flutter-project',
    authDomain: 'freizeitnotes-flutter-project.firebaseapp.com',
    storageBucket: 'freizeitnotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFf3DGNW7mvOl3vu27r8119NtuHUmMc4',
    appId: '1:521427089788:android:c63a5f1e80e52698d08cf9',
    messagingSenderId: '521427089788',
    projectId: 'freizeitnotes-flutter-project',
    storageBucket: 'freizeitnotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcGa11U2VQiFvlI1Lu8OB7whuilz4TfGg',
    appId: '1:521427089788:ios:735d11801402a882d08cf9',
    messagingSenderId: '521427089788',
    projectId: 'freizeitnotes-flutter-project',
    storageBucket: 'freizeitnotes-flutter-project.appspot.com',
    iosBundleId: 'com.example.tutorialFlutter',
  );
}
